### ISSUE TITLE
Convert O(n) routing to trie-based routing.

### ISSUE THREAD

**Issue by patrickt** [tmcgilchrist/airship#19]
Should be a fun little exercise.

**Comment by dkubb** [comment]
A common approach many HTTP routers use would be the patricia/radix trie, but I'd encourage you to also look at the [critbit trie](http://cr.yp.to/critbit.html) and even [ART](http://www3.informatik.tu-muenchen.de/~leis/papers/ART.pdf) (Adaptive Radix Trie). Both should be more efficient, since they focus on reducing the amount of work that needs to be done by the CPU to match a route, and the amount of memory used to store the routes.

**Comment by tmcgilchrist** [comment]
I believe this has been done using `bytestring-trie`
